### ISSUE TITLE
Psalm warns for syntax errors

### ISSUE THREAD

**Issue by NielsdeBlaauw** [pronamic/wp-pronamic-pay-buckaroo#2]
In our automated workflows, Psalm warns for issues regarding syntax errors in some recent changes to this gateway.

Specifically:
```
ERROR: ParseError - plugins/pronamic-ideal/vendor/wp-pay-gateways/buckaroo/src/Gateway.php:470:5 - Syntax error, unexpected T_NS_SEPARATOR, expecting ',' or ']' or ')' on line 470 (see https://psalm.dev/173)
				\
```
and
```
ERROR: ParseError - plugins/pronamic-ideal/vendor/wp-pay-gateways/buckaroo/src/Gateway.php:472:75 - Syntax error, unexpected ',' on line 472 (see https://psalm.dev/173)
				null === $data ? '' : \base64_encode( \md5( $request_content, true ) ),
```

The issues are also noted in the commit that introduced them: https://github.com/wp-pay-gateways/buckaroo/commit/db53d8e061ee6398e20a599d50e0af977b44a5c5 by phpstan.

**Comment by rvdsteege** [comment]
Thank you for opening an issue, Niels! We've resolved the issues in https://github.com/wp-pay-gateways/buckaroo/commit/e8fded223536806b34cc10cd4894b3e9db0cee35.
